#!/usr/bin/env bash
# Vendor the Mermaid runtime into the repository so generated HTML can render
# diagrams WITHOUT any CDN reference (要件: CDN 直参照は禁止 / vendor 同梱).
#
# Why the single-file UMD build (mermaid.min.js) and not the ESM build?
#  - The ESM build (mermaid.esm.min.mjs) lazy-loads hundreds of chunk files; you
#    cannot vendor it as one asset and you cannot attach SRI to `import`.
#  - The UMD build is one self-contained file, loadable via
#    <script src integrity crossorigin>, which lets us pin a SHA-384 hash.
#
# Usage:
#   tools/rr/scripts/vendor-mermaid.sh [VERSION]
# Default VERSION is read from VENDOR_MERMAID_VERSION below.
set -euo pipefail

VERSION="${1:-10.9.1}"

# Resolve repo-relative paths from this script's location (works from any cwd).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RR_DIR="$(dirname "$SCRIPT_DIR")"                 # tools/rr
DEST_DIR="$RR_DIR/assets/vendor/mermaid/$VERSION"
LOCK_FILE="$RR_DIR/assets/vendor/vendor.lock"

echo "Vendoring mermaid@$VERSION -> $DEST_DIR"
mkdir -p "$DEST_DIR"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Fetch the exact tarball URL npm records for this version, then extract.
TARBALL_URL="$(npm view "mermaid@$VERSION" dist.tarball)"
echo "tarball: $TARBALL_URL"
curl -fsSL "$TARBALL_URL" -o "$TMP/mermaid.tgz"
tar -xzf "$TMP/mermaid.tgz" -C "$TMP"

SRC="$TMP/package/dist/mermaid.min.js"
if [ ! -f "$SRC" ]; then
  echo "ERROR: $SRC not found in the tarball (build layout changed?)." >&2
  exit 1
fi
cp "$SRC" "$DEST_DIR/mermaid.min.js"

# Compute the SRI hash for the <script integrity> attribute.
HASH="sha384-$(openssl dgst -sha384 -binary "$DEST_DIR/mermaid.min.js" | openssl base64 -A)"
echo "integrity: $HASH"

# Record version + hash so templates and CI can verify integrity.
{
  echo "# Auto-generated by scripts/vendor-mermaid.sh. Do not edit by hand."
  echo "mermaid $VERSION $HASH"
} > "$LOCK_FILE"

echo "Done. Committed files:"
echo "  $DEST_DIR/mermaid.min.js"
echo "  $LOCK_FILE"
